"""add api_clients

Revision ID: 37ea193e5d6d
Revises: 46a3098e01f4
Create Date: 2026-02-12 20:38:27.473566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ea193e5d6d'
down_revision: Union[str, Sequence[str], None] = '46a3098e01f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_clients_api_key_hash'), 'api_clients', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_api_clients_tenant_id'), 'api_clients', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_clients_tenant_id'), table_name='api_clients')
    op.drop_index(op.f('ix_api_clients_api_key_hash'), table_name='api_clients')
    op.drop_table('api_clients')
    # ### end Alembic commands ###
