"""unique report identity

Revision ID: 5b33babd424f
Revises: e859df4bad85
Create Date: 2026-02-13 17:45:56.881338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b33babd424f'
down_revision: Union[str, Sequence[str], None] = 'e859df4bad85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_report_identity', 'reports', ['tenant_id', 'decision_event_id', 'explanation_id', 'template_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_report_identity', 'reports', type_='unique')
    # ### end Alembic commands ###
