"""add report revisions

Revision ID: 6283a6f63ce4
Revises: 69c91ea304af
Create Date: 2026-02-13 19:22:00.328940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6283a6f63ce4'
down_revision: Union[str, Sequence[str], None] = '69c91ea304af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_client_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_revisions_report_id'), 'report_revisions', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_revisions_tenant_id'), 'report_revisions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_report_revisions_version'), 'report_revisions', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_revisions_version'), table_name='report_revisions')
    op.drop_index(op.f('ix_report_revisions_tenant_id'), table_name='report_revisions')
    op.drop_index(op.f('ix_report_revisions_report_id'), table_name='report_revisions')
    op.drop_table('report_revisions')
    # ### end Alembic commands ###
