"""report audit + version

Revision ID: 69c91ea304af
Revises: 26d9a0e75faf
Create Date: 2026-02-13 18:37:24.761102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c91ea304af'
down_revision: Union[str, Sequence[str], None] = '26d9a0e75faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reports', sa.Column('updated_by_client_id', sa.String(length=36), nullable=True))
    op.add_column('reports', sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('finalized_by_client_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'finalized_by_client_id')
    op.drop_column('reports', 'finalized_at')
    op.drop_column('reports', 'updated_by_client_id')
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'version')
    # ### end Alembic commands ###
