"""add reports

Revision ID: bf5901a6c3a2
Revises: f1cf4f2b0579
Create Date: 2026-02-12 21:38:06.529327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5901a6c3a2'
down_revision: Union[str, Sequence[str], None] = 'f1cf4f2b0579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('decision_event_id', sa.String(length=36), nullable=False),
    sa.Column('explanation_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('report_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_event_id'], ['decision_events.id'], ),
    sa.ForeignKeyConstraint(['explanation_id'], ['explanations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_decision_event_id'), 'reports', ['decision_event_id'], unique=False)
    op.create_index(op.f('ix_reports_explanation_id'), 'reports', ['explanation_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_explanation_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_decision_event_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
