"""report schema_version

Revision ID: e859df4bad85
Revises: bf5901a6c3a2
Create Date: 2026-02-12 21:58:59.360898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e859df4bad85'
down_revision: Union[str, Sequence[str], None] = 'bf5901a6c3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "reports",
        sa.Column("schema_version", sa.String(length=8), nullable=False, server_default="1.0"),
    )
    op.add_column(
        "reports",
        sa.Column("template_version", sa.String(length=16), nullable=False, server_default="1"),
    )

    # opcional: quitar defaults para futuras inserts (si quieres obligar a setearlo desde app)
    op.alter_column("reports", "schema_version", server_default=None)
    op.alter_column("reports", "template_version", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'template_version')
    op.drop_column('reports', 'schema_version')
    # ### end Alembic commands ###
