"""add explanations

Revision ID: f1cf4f2b0579
Revises: 37ea193e5d6d
Create Date: 2026-02-12 20:53:02.446406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cf4f2b0579'
down_revision: Union[str, Sequence[str], None] = '37ea193e5d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('decision_event_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_event_id'], ['decision_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_decision_event_id'), 'explanations', ['decision_event_id'], unique=False)
    op.create_index(op.f('ix_explanations_status'), 'explanations', ['status'], unique=False)
    op.create_index(op.f('ix_explanations_tenant_id'), 'explanations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explanations_tenant_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_status'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_decision_event_id'), table_name='explanations')
    op.drop_table('explanations')
    # ### end Alembic commands ###
